import discord
from discord.ext import commands
from discord import app_commands
import random
import aiohttp

class FunCommands(commands.Cog):
    """Fun and entertaining commands"""
    
    def __init__(self, bot):
        self.bot = bot
        
        self.facts_db = {
            "animal": [
                "🦒 A giraffe's tongue can be up to 20 inches long!",  
                "🐙 Octopuses have three hearts!",  
                "🦘 Kangaroos can't walk backwards!",  
                "🦥 Sloths can hold their breath for up to 40 minutes underwater!",  
                "🦎 Axolotls can regenerate entire limbs!",  
                "🐝 Honey never spoils - archaeologists found 3000-year-old edible honey!",  
                "🐬 Dolphins have names for each other!",  
                "🦦 Sea otters hold hands when they sleep so they don't drift apart!",  
                "🐧 Penguins propose with pebbles!",  
                "🦅 Eagles can see 4-5 times farther than humans!",  
                "🦇 Bats are the only mammals that can truly fly!",  
                "🐨 Koalas sleep 18-22 hours a day!",  
                "🦈 Sharks existed before trees!",  
                "🐢 Turtles can breathe through their butts!",  
                "🦀 Coconut crabs can crack coconuts with their claws!",  
                "🦉 Owls can rotate their heads 270 degrees!",  
                "🦔 Hedgehogs self-anoint with frothy saliva!",  
                "🦑 Squids have blue blood!",  
                "🐊 Crocodiles can't stick their tongues out!",  
                "🦖 Some dinosaurs had feathers!",  
                "🦌 Deer have rectangular pupils!",  
                "🐅 Tigers have striped skin as well as striped fur!",  
                "🐒 Capuchin monkeys use tools to crack nuts!",  
                "🦏 Rhinos can run faster than humans!",  
                "🦥 Sloths can turn their heads almost all the way around!",  
                "🐍 Snakes can sense earthquakes!",  
                "🐡 Pufferfish can inflate themselves to 3 times their size!",  
                "🦛 Hippos produce their own natural sunscreen!",  
                "🐆 Leopards can drag prey twice their weight up a tree!",  
                "🦜 Parrots can live up to 80 years!",  
                "🦢 Swans mate for life!",  
                "🦔 Hedgehogs can hibernate up to 6 months!",  
                "🐕 Dogs can hear frequencies four times higher than humans!",  
                "🐈 Cats have whiskers on the backs of their front legs too!",  
                "🦦 Otters have the densest fur in the animal kingdom!",  
                "🦉 Barn owls can hunt in complete darkness!",  
                "🐠 Clownfish can change their sex!",  
                "🦑 Giant squids have eyes the size of basketballs!",  
                "🐖 Pigs can get sunburned!",  
                "🦎 Chameleons can move their eyes independently!",  
                "🦋 Butterflies taste with their feet!",  
                "🦀 Fiddler crabs wave to communicate!",  
                "🦓 Zebras’ stripes are like human fingerprints!",  
                "🐫 Camels have three sets of eyelids to protect from sand!",  
                "🦔 Hedgehogs can run at 4 mph!",  
                "🐠 Seahorses are the only animals where males give birth!",  
                "🦥 Sloths can turn green from algae growing on them!",  
                "🐺 Wolves howl to assemble the pack!",  
                "🦈 Great white sharks can detect one drop of blood in 25 gallons of water!",  
                "🐊 Alligators can regrow teeth over 50 times in their lifetime!",  
                "🦍 Gorillas can catch human colds!",  
                "🐘 Elephants can communicate using infrasound!",  
                "🦌 Male reindeer grow and shed antlers every year!",  
                "🐓 Chickens have better color vision than humans!",  
                "🦢 Cygnets imprint on the first moving thing they see!",  
                "🦏 Rhinoceros horns are made of keratin!",  
                "🐍 Some snakes can fly for short distances!",  
                "🦖 Velociraptors were covered in feathers!",  
                "🦑 Squids have three hearts and blue blood!",  
                "🐠 Pufferfish carry a toxin deadly to humans!",  
                "🦦 Sea otters use rocks as tools to open shells!",  
                "🦚 Peacocks can sleep in trees!",  
                "🦩 Flamingos can drink boiling water!",  
                "🐝 Bumblebees can fly in the rain!",  
                "🦛 Hippos can hold their breath for 5 minutes!",  
                "🐅 Tiger cubs are born blind!",  
                "🦄 Narwhal tusks are actually elongated teeth!",  
                "🦞 Lobsters taste with their legs!",  
                "🐧 Emperor penguins can survive -40°F winters!",  
                "🦖 Some dinosaurs were smaller than chickens!",  
                "🦦 River otters can close their ears underwater!",  
                "🦘 Kangaroo mothers can pause their pregnancy!",  
                "🦉 Screech owls have asymmetrical ears!",  
                "🐠 Lionfish are venomous!",  
                "🦈 Hammerhead sharks have 360-degree vision!",  
                "🦥 Sloths poop only once a week!",  
                "🐘 Elephants can distinguish human languages!",  
                "🦋 Some butterflies migrate thousands of miles!",  
                "🦑 Colossal squids have hooks on their tentacles!",  
                "🐊 Crocodiles can live up to 100 years!",  
                "🦍 Silverback gorillas lead the troop and protect it!",  
                "🐝 Bees communicate through dance!",  
                "🦀 Crabs can walk sideways but not forward!",  
                "🦜 Some parrots can mimic over 100 words!",  
                "🦏 White rhinos can weigh up to 5,000 pounds!",  
                "🐍 Some snakes can survive up to a year without food!",  
                "🦖 Spinosaurus could swim!",  
                "🦦 Otters have a favorite rock they carry around!",  
                "🐆 Cheetahs can accelerate from 0 to 60 mph in 3 seconds!",  
                "🦢 Swans can live over 20 years in the wild!",  
                "🦩 Flamingos are born gray and turn pink from diet!",  
                "🐘 Elephants mourn their dead!",  
                "🦎 Some lizards can squirt blood from their eyes!",  
                "🦞 Lobsters can live over 50 years!",  
                "🐅 Tigers can swim very well!",  
                "🦉 Owls have silent flight!",  
                "🦒 Giraffes have the same number of neck vertebrae as humans!",  
                "🐙 Octopuses can squeeze through holes the size of a coin!",  
                "🦦 Otters have been observed holding hands to form 'rafts'!",  
                "🦢 Swans have an aggressive territorial nature!",  
                "🦏 Rhinos can run up to 30 mph!",  
                "🐠 Seahorses use tails to anchor themselves!",  
                "🦥 Sloths move so slowly algae can grow on them!",  
                "🦎 Some geckos can walk on water for a few seconds!",  
                "🦄 Narwhals are known as the 'unicorns of the sea'!",  
                "🐊 Crocodiles have a very strong bite force!",  
                "🐝 Honeybees can recognize human faces!",  
                "🦈 Whale sharks are the largest fish on Earth!",  
                "🐍 King cobras can 'stand up' and look a human in the eye!",  
                "🦖 Dinosaurs had hollow bones to stay light!",  
                "🦋 Some moths have ears on their wings to detect bats!",  
                "🐘 Elephants can smell water up to 12 miles away!"  

            ],
            "car": [
                "🚗 The first car to break 100 mph was the 1905 Darracq!",  
                "🏎️ Formula 1 cars can accelerate from 0-60 mph in under 2.5 seconds!",  
                "🚙 The Bugatti Veyron has 10 radiators to keep it cool!",  
                "🚘 Electric cars produce zero tailpipe emissions!",  
                "🚓 The Dodge Challenger Hellcat has over 700 horsepower!",  
                "🚕 The first taxi company started in 1897 in London!",  
                "🏁 The land speed record is held by the ThrustSSC at 763 mph!",  
                "🚐 Minivans were originally called 'family wagons'!",  
                "🚜 Tractors were initially steam-powered before gasoline engines!",  
                "🚗 The world’s first hybrid car was the 1900 Lohner-Porsche!",  
                "🏎️ McLaren F1 has a top speed of 240 mph!",  
                "🚙 SUVs originally stood for 'Sport Utility Vehicle' for off-road use!",  
                "🚘 Some modern cars can park themselves with advanced sensors!",  
                "🚓 Police cars can exceed 200 mph in pursuit versions!",  
                "🚕 The world’s longest taxi line was 68 cars in South Korea!",  
                "🏁 NASCAR cars use over 2,500 horsepower in total race setup!",  
                "🚗 Rolls-Royce engines are hand-assembled!",  
                "🚙 The Tesla Model S Plaid can go 0-60 mph in under 2 seconds!",  
                "🚘 The first windshield wipers were hand-operated!",  
                "🚓 BMW makes police vehicles in several countries!",  
                "🚗 The DeLorean DMC-12 stainless steel body never needs painting!",  
                "🏎️ Lamborghini cars were originally tractors!",  
                "🚙 SUVs like the Hummer H1 were inspired by military Humvees!",  
                "🚐 The Volkswagen Microbus became a symbol of the 60s counterculture!",  
                "🚗 Electric cars like the Nissan Leaf use lithium-ion batteries!",  
                "🏁 The 24 Hours of Le Mans is the world’s oldest endurance race!",  
                "🚓 Some police cars are equipped with license plate scanners!",  
                "🚘 Porsche 911 engines are located at the rear!",  
                "🚙 Jeep Wranglers are the direct descendants of WWII Jeeps!",  
                "🚗 Aston Martin once made a car that could float on water!",  
                "🏎️ Formula E cars race entirely electric!",  
                "🚕 London black cabs require drivers to memorize 25,000 streets!",  
                "🚓 Lamborghini Urus is the fastest SUV in the world!",  
                "🚘 Koenigsegg Jesko can produce up to 1,600 horsepower!",  
                "🚙 The Toyota Corolla is the best-selling car in history!",  
                "🚗 Some luxury cars use laser headlights!",  
                "🏁 The Bugatti Chiron has a top speed limited to 261 mph for safety!",  
                "🚐 Mercedes-Benz Sprinter vans can be converted into tiny homes!",  
                "🚓 Some police cars have ballistic protection!",  
                "🚘 The McLaren P1 has hybrid technology for performance!",  
                "🚙 The Hennessey Venom F5 is designed to reach 311 mph!",  
                "🚗 Hybrid cars can switch between electric and gas automatically!",  
                "🏎️ The fastest accelerating production car is the Rimac Nevera!",  
                "🚙 Jeep has produced over 9 million vehicles since 1941!",  
                "🚓 Some countries use Tesla Model X as police vehicles!",  
                "🚘 Mercedes-Benz invented the first internal combustion car in 1886!",  
                "🚗 Some cars have night vision to detect pedestrians!",  
                "🏁 IndyCar engines rev up to 12,000 RPM!",  
                "🚙 SUVs often have lower fuel efficiency due to weight!",  
                "🚕 The first electric taxi fleet ran in 1897 in New York!",  
                "🚓 Dodge Chargers are often used as police interceptors!",  
                "🚘 Bugatti engines have 16 cylinders!",  
                "🚗 Porsche makes engines in-house to ensure perfection!",  
                "🏎️ Some race cars change tires in under 2 seconds!",  
                "🚙 The Jeep Wrangler can drive through over 30 inches of water!",  
                "🚐 Minivans often use sliding doors for family convenience!",  
                "🚓 Police vehicles use reinforced bumpers for pursuits!",  
                "🚘 Tesla autopilot can steer, accelerate, and brake automatically!",  
                "🚗 The Ford Mustang was first introduced in 1964!",  
                "🏁 Formula 1 tires wear out in under 50 miles during a race!",  
                "🚙 Subaru cars are known for symmetrical all-wheel drive!",  
                "🚕 Modern taxis now often use hybrid or electric vehicles!",  
                "🚓 Some police cars have intercooler-equipped engines!",  
                "🚘 Ferrari V12 engines are handcrafted by a single engineer!",  
                "🚗 Cars have catalytic converters to reduce harmful emissions!",  
                "🏎️ Koenigsegg Regera uses a hybrid system with no traditional gearbox!",  
                "🚙 SUVs like the Range Rover were initially luxury off-roaders!",  
                "🚐 The Ford Transit is one of the most popular commercial vans worldwide!",  
                "🚓 Some police cars have roof-mounted cameras for traffic monitoring!",  
                "🚘 BMW i8 is a plug-in hybrid sports car!",  
                "🚗 Some hypercars cost over $3 million!",  
                "🏁 Le Mans-winning cars must meet strict endurance regulations!",  
                "🚙 The Jeep Grand Cherokee can tow over 7,000 pounds!",  
                "🚕 Yellow cabs in NYC became iconic in 1907!",  
                "🚓 Police interceptors can accelerate faster than civilian versions!",  
                "🚘 The Koenigsegg Agera RS held the world speed record in 2017!",  
                "🚗 Some modern cars use carbon fiber to reduce weight!",  
                "🏎️ McLaren Senna is named after legendary F1 driver Ayrton Senna!",  
                "🚙 SUVs are popular for both off-road and urban use!",  
                "🚐 VW Campervans were used in WWII as staff vehicles!",  
                "🚓 Some police cars carry spike strips to stop fleeing vehicles!",  
                "🚘 The Tesla Cybertruck has nearly indestructible stainless steel body!",  
                "🚗 Ford F-150 has been the best-selling truck in the U.S. for decades!",  
                "🏁 Formula 1 cars have more downforce than some fighter jets!",  
                "🚙 Subaru WRX is inspired by rally racing!",  
                "🚕 Some taxis use digital meters for accurate fares!",  
                "🚓 Dodge Durango Pursuit is a modern police SUV!",  
                "🚘 Mercedes-AMG engines are built by a single technician from start to finish!",  
                "🚗 Some concept cars have doors that open like wings!",  
                "🏎️ The fastest Bugatti in the world is capable of 304 mph!"  

            ],
            "human": [
                "🧠 The human brain contains around 86 billion neurons!",  
                "👁️ Your eyes can distinguish about 10 million different colors!",  
                "🦴 The adult human skeleton has 206 bones!",  
                "💓 Your heart beats about 100,000 times a day!",  
                "🧬 Humans share about 98.8% of their DNA with chimpanzees!",  
                "👃 Your nose can remember 50,000 different scents!",  
                "🦵 The femur is the strongest bone in the human body!",  
                "🦷 Enamel on your teeth is the hardest substance in the human body!",  
                "🩸 Your blood travels around your body in under a minute!",  
                "👂 Humans can hear frequencies between 20 Hz and 20 kHz!",  
                "🖐️ Fingernails grow about 3 mm per month!",  
                "🦵 Muscles make up about 40% of a human’s body weight!",  
                "🫀 The human heart creates enough pressure to squirt blood 30 feet!",  
                "🫁 Lungs contain over 300 million alveoli!",  
                "👅 Your tongue print is unique, just like your fingerprints!",  
                "🫀 Women’s hearts beat slightly faster than men’s!",  
                "🦠 Your body contains trillions of microorganisms!",  
                "🧠 The brain generates about 20 watts of electrical power!",  
                "👀 Your blink lasts about 100–400 milliseconds!",  
                "🦴 Babies are born with around 270 bones, some fuse over time!",  
                "🩸 Blood makes up about 7% of your body weight!",  
                "🧬 Humans share 50% of their DNA with bananas!",  
                "🦵 The strongest muscle in terms of endurance is the heart!",  
                "🦷 Humans produce about 1–1.5 liters of saliva per day!",  
                "🧠 Your brain uses 20% of the oxygen you breathe!",  
                "👁️ The cornea is the only part of the body without a blood supply!",  
                "🖐️ Your fingertips have about 2,500 touch receptors per square centimeter!",  
                "🦵 The gluteus maximus is the largest muscle in the body!",  
                "🧠 The human brain can generate new neurons throughout life!",  
                "🦷 Your teeth start forming before you are born!",  
                "🫁 The surface area of your lungs is roughly the size of a tennis court!",  
                "🧠 Memories are stored by changing the strength of synapses!",  
                "🦠 Human stomachs contain hydrochloric acid strong enough to dissolve metal!",  
                "🫁 You breathe in about 11,000 liters of air every day!",  
                "🦵 Your legs contain about half of all the muscles in your body!",  
                "🧠 Human brains are more active at night than during the day!",  
                "🦷 Teeth are harder than bone!",  
                "👁️ Your eye can process 36,000 pieces of information per hour!",  
                "🦵 The Achilles tendon is the strongest tendon in the body!",  
                "🖐️ Your hands have more sensory neurons than any other part of your body!",  
                "🫀 Your heart pumps around 2,000 gallons of blood per day!",  
                "🦠 Your skin sheds around 30,000–40,000 dead cells every minute!",  
                "🧬 Humans can detect pheromones subconsciously!",  
                "🦷 Molars are designed to crush, while canines tear!",  
                "🧠 The average brain weighs about 3 pounds!",  
                "🦵 Humans can survive with only one kidney!",  
                "👁️ The retina contains more than 120 million rods for vision!",  
                "🦴 Your bones are constantly being remodeled!",  
                "🫀 The heart creates enough energy in a day to drive a truck for 20 miles!",  
                "🧠 Your brain operates on the same amount of power as a 20-watt light bulb!",  
                "🦷 Humans have four different types of teeth: incisors, canines, premolars, molars!",  
                "🦵 The smallest bone in your body is the stapes in the ear!",  
                "🫁 Your diaphragm moves about 2,000 times per day!",  
                "🧠 Neurons in the brain can fire at over 200 mph!",  
                "🦴 Bone is about five times stronger than steel of the same density!",  
                "🫀 Your heartbeat changes depending on your mood!",  
                "🦠 The human body has more bacterial cells than human cells!",  
                "🖐️ Each hand has 27 bones!",  
                "🦷 Wisdom teeth are vestigial remnants of our ancestors!",  
                "🧬 Humans have about 20,000–25,000 genes!",  
                "🦵 Your hamstrings are twice as long as your quadriceps!",  
                "👁️ Eyes can get sunburned from UV light!",  
                "🦠 The acid in your stomach kills most bacteria you ingest!",  
                "🫁 You take about 20,000 breaths every day!",  
                "🦴 Bones store minerals like calcium and phosphorus!",  
                "🧠 Brain size does not determine intelligence!",  
                "🦷 Teeth start decaying immediately if not cared for properly!",  
                "🖐️ Humans have opposable thumbs to manipulate objects!",  
                "🦵 Walking burns roughly 100 calories per mile!",  
                "🫀 The pulse in your wrist is caused by your heart pumping blood!",  
                "🧠 The human brain is 60% fat!",  
                "🦠 Human bodies produce their own aspirin!",  
                "🦷 Tooth enamel is the hardest substance in the body!",  
                "🦵 Humans can run about 15–20 mph on average for short sprints!",  
                "🖐️ Fingerprints are unique to every individual!",  
                "🧬 Humans can interbreed with Neanderthals, leaving DNA traces!",  
                "🦴 Bone marrow produces red and white blood cells!",  
                "🫁 Coughing clears your airways with speeds up to 60 mph!",  
                "🧠 Humans have about 100,000 miles of blood vessels!",  
                "🦷 Teeth are as unique as a fingerprint!",  
                "🦵 Humans have about 650 muscles!",  
                "👁️ Your eyes blink roughly 15-20 times per minute!",  
                "🦠 Fingernails grow faster on your dominant hand!",  
                "🫀 The heart generates enough electricity to power a small lightbulb!"  

            ],
            "history": [
                "🏰 The Great Wall of China is over 13,000 miles long!",  
                "⚔️ The shortest war in history was between Britain and Zanzibar in 1896—it lasted 38 minutes!",  
                "👑 Cleopatra lived closer in time to the moon landing than to the construction of the Great Pyramid!",  
                "🗽 The Statue of Liberty was a gift from France in 1886!",  
                "💣 The first nuclear bomb was detonated in 1945 in New Mexico!",  
                "🛡️ Vikings never wore horned helmets—they’re a myth!",  
                "🗡️ Genghis Khan’s empire was the largest contiguous empire in history!",  
                "📜 The Rosetta Stone helped decode Egyptian hieroglyphs!",  
                "🚀 Yuri Gagarin was the first human in space in 1961!",  
                "🛶 The first Olympic Games were held in 776 BCE in Greece!",  
                "🏺 The Library of Alexandria was one of the largest libraries in the ancient world!",  
                "⚓ The Titanic sank in 1912 after hitting an iceberg!",  
                "🪖 The Mongol army was known for its speed and discipline!",  
                "🏛️ The Colosseum could hold up to 80,000 spectators!",  
                "🔥 The Great Fire of London in 1666 destroyed much of the city but killed few people!",  
                "🎖️ Napoleon was not actually short—he was around 5’7”!",  
                "💡 Thomas Edison held over 1,000 patents!",  
                "🗿 Easter Island statues weigh up to 82 tons each!",  
                "⚔️ Samurai were the warrior class in feudal Japan!",  
                "📖 The Gutenberg Bible was the first book printed with movable type!",  
                "🛡️ The medieval knight’s armor could weigh over 60 pounds!",  
                "🚢 The first successful steamship was built in 1807!",  
                "🕰️ The French Revolution began in 1789!",  
                "🏛️ The Parthenon in Athens was built in 447 BCE!",  
                "⚔️ The Black Death killed up to 60% of Europe’s population!",  
                "📜 Hammurabi’s Code is one of the oldest written laws!",  
                "🛡️ The Battle of Thermopylae in 480 BCE had 300 Spartans fighting thousands of Persians!",  
                "🗡️ The Renaissance began in Italy in the 14th century!",  
                "🗺️ Marco Polo traveled to China in the 13th century!",  
                "💣 World War I started in 1914 and ended in 1918!",  
                "🛶 The Vikings discovered North America around 1000 CE!",  
                "🏰 The Tower of London was built in 1078!",  
                "⚔️ The Hundred Years’ War lasted 116 years!",  
                "🏺 The Sphinx in Egypt is over 4,500 years old!",  
                "🎖️ Joan of Arc led the French army in the 15th century!",  
                "🗽 The Berlin Wall fell in 1989!",  
                "🪖 Alexander the Great conquered most of the known world by age 30!",  
                "📖 The Magna Carta was signed in 1215!",  
                "🛡️ The Crusades lasted from 1096 to 1291!",  
                "🗡️ Genghis Khan’s real name was Temujin!",  
                "⚓ Christopher Columbus sailed to the Americas in 1492!",  
                "🔥 The Great Fire of Rome occurred in 64 AD!",  
                "🏰 The Norman Conquest of England happened in 1066!",  
                "💡 Leonardo da Vinci painted the Mona Lisa between 1503 and 1506!",  
                "🗿 Stonehenge was built around 3000 BCE!",  
                "🛶 The Silk Road connected Europe and Asia for centuries!",  
                "⚔️ The Battle of Hastings determined the English throne in 1066!",  
                "🏛️ The Pantheon in Rome has a dome that is still the largest unreinforced concrete dome!",  
                "📜 The Dead Sea Scrolls were discovered in the 1940s!",  
                "🪖 The American Civil War lasted from 1861 to 1865!",  
                "🛡️ Knights used jousting as training for battle!",  
                "🗡️ The Roman Empire fell in 476 AD!",  
                "🚀 Sputnik 1 was the first artificial satellite in 1957!",  
                "🎖️ The Wright brothers made the first powered flight in 1903!",  
                "🏺 Ancient Egyptians invented paper from papyrus!",  
                "⚓ The Panama Canal opened in 1914!",  
                "🔥 The Great Fire of Chicago happened in 1871!",  
                "🏰 Machu Picchu was built in the 15th century!",  
                "🗺️ Ferdinand Magellan’s expedition was the first to circumnavigate the globe!",  
                "💡 Benjamin Franklin invented the lightning rod!",  
                "🛶 The Mayans had advanced knowledge of astronomy!",  
                "🗽 The Statue of Liberty’s torch was replaced in 1986!",  
                "⚔️ The Siege of Constantinople in 1453 marked the end of the Byzantine Empire!",  
                "🏛️ The Roman Colosseum hosted gladiator fights for centuries!",  
                "🪖 Spartacus led a slave revolt against Rome in 73 BCE!",  
                "📖 The Iliad and The Odyssey are attributed to Homer!",  
                "🕰️ The Industrial Revolution began in the 18th century!",  
                "🛡️ The Knights Templar were disbanded in 1312!",  
                "🗡️ The Samurai code is called Bushido!",  
                "⚓ The Mayflower carried the Pilgrims to America in 1620!",  
                "🏺 Ancient Greeks held the Olympics every 4 years to honor Zeus!",  
                "🎖️ The Vietnam War lasted from 1955 to 1975!",  
                "🗿 Moai statues on Easter Island were carved between 1400 and 1650!",  
                "💣 The Cold War never turned into a full-scale war but lasted from 1947 to 1991!",  
                "🏰 Neuschwanstein Castle in Germany inspired Disney’s castle!",  
                "🛶 The Terracotta Army was buried with China’s first emperor in 210 BCE!",  
                "⚔️ The Peloponnesian War lasted 27 years between Athens and Sparta!",  
                "🏛️ The Acropolis was a fortress and temple complex in ancient Athens!",  
                "🧱 The Berlin Wall divided East and West Berlin for 28 years!",  
                "📜 The Enlightenment changed philosophy and science in the 17th and 18th centuries!",  
                "🗡️ The Ottoman Empire lasted over 600 years!",  
                "🪖 Hannibal crossed the Alps with elephants during the Second Punic War!",  
                "🚀 The Apollo 11 mission landed humans on the moon in 1969!",  
                "⚓ Vasco da Gama was the first to sail directly from Europe to India!",  
                "💡 Archimedes invented war machines to defend Syracuse!",  
                "🏺 Ancient Romans built aqueducts to carry water over long distances!"  

            ],
            "random": [
                "🌌 Space smells like seared steak!",  
                "🍫 White chocolate isn’t technically chocolate!",  
                "🐘 Elephants can recognize themselves in mirrors!",  
                "🦑 The heart of a blue whale is the size of a small car!",  
                "🌋 Lightning strikes produce Ozone which smells fresh after rain!",  
                "🕷️ Spiders can’t fly, but some use their silk to ‘balloon’ through the air!",  
                "🎨 The Mona Lisa has no eyebrows—they were likely removed during cleaning!",  
                "🧊 Antarctica is the driest place on Earth!",  
                "🐟 Some fish can climb waterfalls!",  
                "🍌 Bananas are berries but strawberries aren’t!",  
                "🦦 Otters hold hands so they don’t drift apart while sleeping!",  
                "🌙 There are ‘moonquakes’ similar to earthquakes on the Moon!",  
                "🦄 Narwhal tusks can sense water temperature and pressure!",  
                "🌎 Earth’s rotation is gradually slowing down!",  
                "🐝 Bees can recognize human faces!",  
                "🦎 Some lizards can squirt blood from their eyes!",  
                "🎵 Listening to music releases dopamine in your brain!",  
                "🦋 Butterflies can taste with their feet!",  
                "🌪️ Tornadoes can lift objects weighing tons!",  
                "🧬 Humans share about 60% of their DNA with bananas!",  
                "🦞 Lobsters taste with their legs and chew with their stomach!",  
                "⚡ Lightning strikes hotter than the surface of the Sun!",  
                "🦔 Hedgehogs can run up to 4 mph!",  
                "🐧 Penguins propose with pebbles!",  
                "🍯 Honey never spoils—even 3000-year-old honey is edible!",  
                "🌊 Waves on Neptune are made of liquid diamond!",  
                "🦜 Parrots can live up to 80 years!",  
                "🦇 Bats are the only mammals that can fly!",  
                "🧊 Water can boil and freeze at the same time under the right pressure!",  
                "🐌 Some snails can sleep for 3 years!",  
                "🦁 Lions are the only cats that live in groups called prides!",  
                "🛸 Some metals can ‘remember’ their shape after being bent!",  
                "🦖 Dinosaurs lived closer to the moon landing than the building of the pyramids!",  
                "🍎 Apples float in water because 25% of their volume is air!",  
                "🐢 Turtles can breathe through their butts!",  
                "🌍 There’s enough DNA in your body to stretch from the Sun to Pluto and back!",  
                "🦑 Squids have three hearts!",  
                "🦥 Sloths can hold their breath for up to 40 minutes underwater!",  
                "💡 Humans have been using fire for over 1 million years!",  
                "🧊 Antarctica has a ‘Blood Falls’ that’s actually red iron oxide!",  
                "🐙 Octopuses can taste with their arms!",  
                "🦩 Flamingos are born gray and turn pink from their diet!",  
                "🎲 The oldest known board game is over 5,000 years old!",  
                "🌌 A teaspoon of a neutron star would weigh about 6 billion tons!",  
                "🦓 Zebras’ stripes are unique like fingerprints!",  
                "🐶 Dogs can smell your feelings!",  
                "🧠 Your brain can survive for 6 minutes without oxygen before permanent damage!",  
                "🎃 Pumpkins are berries!",  
                "🦈 Sharks existed before trees!",  
                "🦚 Peacocks can sleep in trees to stay safe from predators!",  
                "🌞 Sunlight takes 8 minutes to reach Earth!",  
                "🦀 Coconut crabs can crack coconuts with their claws!",  
                "🦌 Deer have rectangular pupils!",  
                "🌊 The Amazon River can discharge more water than the next seven largest rivers combined!",  
                "🦏 Rhinos can weigh up to 5,000 pounds!",  
                "🧊 There are ‘ice circles’ that naturally form in rivers!",  
                "🐔 Chickens can remember over 100 faces!",  
                "🦔 Hedgehogs can self-anoint with frothy saliva!",  
                "🪐 Saturn could float in water if you had a big enough pool!",  
                "🦅 Eagles can see 4–5 times farther than humans!",  
                "🐎 Horses can sleep both lying down and standing up!",  
                "🦒 Giraffes only need 5–30 minutes of sleep per day!",  
                "🌑 The Moon is moving away from Earth at 1.5 inches per year!",  
                "🦈 Great white sharks can detect one drop of blood in 25 gallons of water!",  
                "🦦 Sea otters have the densest fur in the animal kingdom!",  
                "🦞 Lobsters can live over 50 years!",  
                "🦜 Some birds can see ultraviolet light!",  
                "🐬 Dolphins have names for each other!",  
                "🦩 Flamingos can drink boiling water!",  
                "🐍 Some snakes can survive for a year without food!",  
                "🦑 Giant squids have eyes the size of basketballs!",  
                "🦍 Gorillas can catch human colds!",  
                "🦋 Some moths have ears on their wings to detect bats!",  
                "🌋 There’s a volcano under Antarctica called Mount Erebus!",  
                "🦖 Some dinosaurs were smaller than chickens!",  
                "🐕 Dogs’ sense of smell is 100,000 times stronger than humans’!",  
                "🦀 Fiddler crabs wave to communicate!",  
                "🦢 Swans mate for life!",  
                "🐉 Komodo dragons can kill with venomous bites!",  
                "🧬 DNA was first discovered in 1869!",  
                "🦠 Your body contains trillions of microorganisms!",  
                "🦎 Chameleons can move their eyes independently!",  
                "🦁 Male lions do 90% of the hunting in a pride!",  
                "🌌 There are more stars in the universe than grains of sand on Earth!",  
                "🦔 Hedgehogs can hibernate up to 6 months!",  
                "🧊 There’s ice on Mercury!",  
                "🐡 Pufferfish carry a toxin deadly to humans!",  
                "🦦 River otters can close their ears underwater!",  
                "🦓 Zebras’ stripes may help repel flies!",  
                "🦏 White rhinos can run up to 30 mph!",  
                "🐉 The Gila monster is one of the few venomous lizards!",  
                "🦞 Crayfish can regenerate lost claws!",  
                "🦢 Cygnets imprint on the first moving object they see!",  
                "🐘 Elephants mourn their dead!",  
                "🦒 Giraffes have the same number of neck vertebrae as humans!",  
                "🦑 Colossal squids have hooks on their tentacles!"  

            ]
        }
        
        self.song_quiz = [
    {"verse": "Is this the real life? Is this just fantasy?", "song": "Bohemian Rhapsody", "artist": "Queen"},
    {"verse": "Just a small town girl, living in a lonely world", "song": "Don't Stop Believin'", "artist": "Journey"},
    {"verse": "I got the eye of the tiger, a fighter", "song": "Eye of the Tiger", "artist": "Survivor"},
    {"verse": "Hello, is it me you're looking for?", "song": "Hello", "artist": "Lionel Richie"},
    {"verse": "We will, we will rock you!", "song": "We Will Rock You", "artist": "Queen"},
    {"verse": "I'm walking on sunshine, whoa-oh", "song": "Walking on Sunshine", "artist": "Katrina and the Waves"},
    {"verse": "Sweet Caroline, bah bah bah", "song": "Sweet Caroline", "artist": "Neil Diamond"},
    {"verse": "Never gonna give you up, never gonna let you down", "song": "Never Gonna Give You Up", "artist": "Rick Astley"},
    {"verse": "Cause baby you're a firework", "song": "Firework", "artist": "Katy Perry"},
    {"verse": "You are my fire, the one desire", "song": "I Want It That Way", "artist": "Backstreet Boys"},
    {"verse": "I see a red door and I want it painted black", "song": "Paint It Black", "artist": "The Rolling Stones"},
    {"verse": "Imagine there's no heaven, it's easy if you try", "song": "Imagine", "artist": "John Lennon"},
    {"verse": "Don't stop me now, I'm having such a good time", "song": "Don't Stop Me Now", "artist": "Queen"},
    {"verse": "I will always love you", "song": "I Will Always Love You", "artist": "Whitney Houston"},
    {"verse": "Baby baby baby ohhh", "song": "Baby", "artist": "Justin Bieber"},
    {"verse": "Cause you know I'd walk a thousand miles", "song": "A Thousand Miles", "artist": "Vanessa Carlton"},
    {"verse": "I'm on the highway to hell", "song": "Highway to Hell", "artist": "AC/DC"},
    {"verse": "I kissed a girl and I liked it", "song": "I Kissed a Girl", "artist": "Katy Perry"},
    {"verse": "All the single ladies, now put your hands up", "song": "Single Ladies", "artist": "Beyoncé"},
    {"verse": "Hey Jude, don't make it bad", "song": "Hey Jude", "artist": "The Beatles"},
    {"verse": "Cause you’re amazing just the way you are", "song": "Just the Way You Are", "artist": "Bruno Mars"},
    {"verse": "I've got sunshine on a cloudy day", "song": "My Girl", "artist": "The Temptations"},
    {"verse": "Hit me baby one more time", "song": "...Baby One More Time", "artist": "Britney Spears"},
    {"verse": "Oops!... I did it again", "song": "Oops!... I Did It Again", "artist": "Britney Spears"},
    {"verse": "Rolling in the deep", "song": "Rolling in the Deep", "artist": "Adele"},
    {"verse": "We're up all night to get lucky", "song": "Get Lucky", "artist": "Daft Punk"},
    {"verse": "I came in like a wrecking ball", "song": "Wrecking Ball", "artist": "Miley Cyrus"},
    {"verse": "I'm too hot, call the police and the fireman", "song": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars"},
    {"verse": "Cause the players gonna play, play, play", "song": "Shake It Off", "artist": "Taylor Swift"},
    {"verse": "It's a beautiful day, don't let it get away", "song": "Beautiful Day", "artist": "U2"},
    {"verse": "Hello from the other side", "song": "Hello", "artist": "Adele"},
    {"verse": "I got a feeling that tonight's gonna be a good night", "song": "I Gotta Feeling", "artist": "The Black Eyed Peas"},
    {"verse": "We found love in a hopeless place", "song": "We Found Love", "artist": "Rihanna"},
    {"verse": "Is it too late now to say sorry?", "song": "Sorry", "artist": "Justin Bieber"},
    {"verse": "I’m on top of the world, hey!", "song": "On Top of the World", "artist": "Imagine Dragons"},
    {"verse": "You're gonna hear me roar", "song": "Roar", "artist": "Katy Perry"},
    {"verse": "I want to hold your hand", "song": "I Want to Hold Your Hand", "artist": "The Beatles"},
    {"verse": "I came to dance, dance, dance, dance", "song": "Dynamite", "artist": "BTS"},
    {"verse": "Nothing compares to you", "song": "Nothing Compares 2 U", "artist": "Sinead O'Connor"},
    {"verse": "Just gonna stand there and watch me burn", "song": "Love the Way You Lie", "artist": "Eminem ft. Rihanna"},
    {"verse": "I’m in love with the shape of you", "song": "Shape of You", "artist": "Ed Sheeran"},
    {"verse": "You're the one that I want", "song": "You're the One That I Want", "artist": "Grease Cast"},
    {"verse": "Hello, darkness, my old friend", "song": "The Sound of Silence", "artist": "Simon & Garfunkel"},
    {"verse": "I can't get no satisfaction", "song": "(I Can't Get No) Satisfaction", "artist": "The Rolling Stones"},
    {"verse": "We are never ever getting back together", "song": "We Are Never Ever Getting Back Together", "artist": "Taylor Swift"},
    {"verse": "Cause all of me loves all of you", "song": "All of Me", "artist": "John Legend"},
    {"verse": "I'm a survivor, I'm not gonna give up", "song": "Survivor", "artist": "Destiny's Child"},
    {"verse": "It’s getting hot in here, so take off all your clothes", "song": "Hot in Herre", "artist": "Nelly"},
    {"verse": "Every breath you take, every move you make", "song": "Every Breath You Take", "artist": "The Police"},
    {"verse": "You're beautiful, it's true", "song": "You're Beautiful", "artist": "James Blunt"},
    {"verse": "I'm too sexy for my shirt", "song": "I'm Too Sexy", "artist": "Right Said Fred"},
    {"verse": "I kissed a girl and I liked it", "song": "I Kissed a Girl", "artist": "Katy Perry"},
    {"verse": "Baby shark, doo doo doo doo doo doo", "song": "Baby Shark", "artist": "Pinkfong"},
    {"verse": "Sing us a song, you're the piano man", "song": "Piano Man", "artist": "Billy Joel"},
    {"verse": "We don't need no education", "song": "Another Brick in the Wall", "artist": "Pink Floyd"},
    {"verse": "It's my life, it's now or never", "song": "It's My Life", "artist": "Bon Jovi"},
    {"verse": "I like big butts and I cannot lie", "song": "Baby Got Back", "artist": "Sir Mix-A-Lot"},
    {"verse": "Call me maybe", "song": "Call Me Maybe", "artist": "Carly Rae Jepsen"},
    {"verse": "Turn down for what!", "song": "Turn Down for What", "artist": "DJ Snake & Lil Jon"},
    {"verse": "I kissed a boy and I liked it", "song": "I Kissed a Girl", "artist": "Katy Perry"},
    {"verse": "Hey, I just met you, and this is crazy", "song": "Call Me Maybe", "artist": "Carly Rae Jepsen"},
    {"verse": "Work, work, work, work, work, work", "song": "Work", "artist": "Rihanna"},
    {"verse": "This hit, that ice cold, Michelle Pfeiffer, that white gold", "song": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars"},
    {"verse": "I'm too hot, hot damn", "song": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars"},
    {"verse": "I'm happy, clap along if you feel like happiness is the truth", "song": "Happy", "artist": "Pharrell Williams"},
    {"verse": "Don't stop believin', hold on to that feeling", "song": "Don't Stop Believin'", "artist": "Journey"},
    {"verse": "I like to move it, move it", "song": "I Like to Move It", "artist": "Reel 2 Real"},
    {"verse": "Party rock is in the house tonight", "song": "Party Rock Anthem", "artist": "LMFAO"},
    {"verse": "You spin me right round, baby right round", "song": "You Spin Me Round", "artist": "Dead or Alive"},
    {"verse": "Somebody once told me the world is gonna roll me", "song": "All Star", "artist": "Smash Mouth"},
    {"verse": "It's the eye of the tiger, it's the thrill of the fight", "song": "Eye of the Tiger", "artist": "Survivor"},
    {"verse": "I see it in your eyes, I see it in your smile", "song": "I Just Called to Say I Love You", "artist": "Stevie Wonder"},
    {"verse": "I'm bringing sexy back", "song": "SexyBack", "artist": "Justin Timberlake"},
    {"verse": "Oops, I did it again", "song": "Oops!... I Did It Again", "artist": "Britney Spears"},
    {"verse": "I want it that way", "song": "I Want It That Way", "artist": "Backstreet Boys"},
    {"verse": "It's a beautiful day, don't let it get away", "song": "Beautiful Day", "artist": "U2"},
    {"verse": "Cause baby you're a firework", "song": "Firework", "artist": "Katy Perry"},
    {"verse": "I came in like a wrecking ball", "song": "Wrecking Ball", "artist": "Miley Cyrus"},
    {"verse": "We found love in a hopeless place", "song": "We Found Love", "artist": "Rihanna"},
    {"verse": "I'm a survivor, I'm not gonna give up", "song": "Survivor", "artist": "Destiny's Child"},
    {"verse": "Hit me baby one more time", "song": "...Baby One More Time", "artist": "Britney Spears"},
    {"verse": "Hello from the other side", "song": "Hello", "artist": "Adele"},
    {"verse": "Every breath you take, every move you make", "song": "Every Breath You Take", "artist": "The Police"},
    {"verse": "I like big butts and I cannot lie", "song": "Baby Got Back", "artist": "Sir Mix-A-Lot"},
    {"verse": "I'm on the top of the world, hey!", "song": "On Top of the World", "artist": "Imagine Dragons"},
    {"verse": "Cause the players gonna play, play, play", "song": "Shake It Off", "artist": "Taylor Swift"},
    {"verse": "I got a feeling that tonight's gonna be a good night", "song": "I Gotta Feeling", "artist": "The Black Eyed Peas"},
    {"verse": "Work, work, work, work, work, work", "song": "Work", "artist": "Rihanna"},
    {"verse": "Turn down for what!", "song": "Turn Down for What", "artist": "DJ Snake & Lil Jon"},
    {"verse": "I'm bringing sexy back", "song": "SexyBack", "artist": "Justin Timberlake"},
    {"verse": "Party rock is in the house tonight", "song": "Party Rock Anthem", "artist": "LMFAO"},
    {"verse": "Somebody once told me the world is gonna roll me", "song": "All Star", "artist": "Smash Mouth"},
    {"verse": "You spin me right round, baby right round", "song": "You Spin Me Round", "artist": "Dead or Alive"},
    {"verse": "I like to move it, move it", "song": "I Like to Move It", "artist": "Reel 2 Real"}
]


        
        self.meme_templates = [
            {"name": "Drake Disapprove/Approve", "emoji": "🦆"},
            {"name": "Distracted Boyfriend", "emoji": "👨‍💼"},
            {"name": "Woman Yelling at Cat", "emoji": "😾"},
            {"name": "This is Fine (Dog in Fire)", "emoji": "🔥🐕"},
            {"name": "Is This a Pigeon?", "emoji": "🦋"},
            {"name": "Roll Safe (Think About It)", "emoji": "🧠"},
            {"name": "Disaster Girl", "emoji": "🔥👧"},
            {"name": "Expanding Brain", "emoji": "🧠✨"},
            {"name": "Two Buttons", "emoji": "🔴🔵"},
            {"name": "Change My Mind", "emoji": "💬"},
            {"name": "Surprised Pikachu", "emoji": "⚡😮"},
            {"name": "Stonks", "emoji": "📈"},
            {"name": "Always Has Been", "emoji": "🔫👨‍🚀"},
            {"name": "Bernie Sanders Mittens", "emoji": "🧤"},
            {"name": "Hide the Pain Harold", "emoji": "😬"}
        ]

async def setup(bot):
    await bot.add_cog(FunCommands(bot))
